version: '3.8'

services:
  app:
    build: .
    container_name: golfclub-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/golfclub?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=golfuser
      - SPRING_DATASOURCE_PASSWORD=golfpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_GOLFCLUB=DEBUG
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - golfclub-network

  mysql:
    image: mysql:8.0
    container_name: golfclub-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: golfclub
      MYSQL_USER: golfuser
      MYSQL_PASSWORD: golfpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - golfclub-network

volumes:
  mysql_data:

networks:
  golfclub-network:
    driver: bridge